#!/usr/bin/env bash

set -e

CONFIG="config/install.conf.yaml"
if [ $# -ne 0 ]; then
    CONFIG="config/$1.conf.yaml"
fi
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -v -d "${BASEDIR}" --plugin-dir dotbot-brew --plugin-dir dotbot-crossplatform --plugin-dir dotbot-omnipkg -c "${CONFIG}" "${@:2}"
