# Scope     type     package
# Supported scopes: all, darwin, ubuntu, arch
# Supported types:     auto, tap, formula, cask, package

all     auto    git
all     auto    git-lfs
all     auto    tmux
all     auto    tmate
all     auto    herdr
all     auto    lazygit
all     auto    zsh
all     auto    jq
ubuntu  package silversearcher-ag
arch    package silver-searcher
darwin  tap     cormacrelf/tap
darwin  tap     nikitabobko/tap
darwin  formula skillshare
darwin  formula mise
darwin  formula dark-notify
darwin  cask    font-fira-code-nerd-font
darwin  cask    karabiner-elements
darwin  cask    wezterm
