# Scope     type     package
# Supported scopes: all, darwin, ubuntu, arch
# Supported types:     auto, tap, formula, cask, package, skill

all     auto    git
all     auto    git-lfs
all     auto    tmux
all     auto    tmate
all     auto    herdr
all     auto    lazygit
all     auto    zsh
all     auto    jq
all     auto    node
all     skill   fiveq/skills
all     skill   dmmulroy/anti-slop
all     skill   backnotprop/plannotator
darwin  tap     cormacrelf/tap
darwin  tap     nikitabobko/tap
darwin  formula mise
darwin  formula dark-notify
darwin  cask    font-fira-code-nerd-font
darwin  cask    karabiner-elements
darwin  cask    wezterm
