
# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

DOTFILES=$HOME/.files
PATH=$DOTFILES/bin:$PATH

# Virtualenvwrapper
WORKON_HOME=$HOME/.envs
if [ "$VIRTUAL_ENV" ]; then 
    source $VIRTUAL_ENV/bin/activate; 
fi 

# Pip 
PIP_VIRTUALENV_BASE=$WORKON_HOME
PIP_RESPECT_VIRTUALENV=true

# System specific settings
if [ -f $DOTFILES/sys.sh ]; then
    source $DOTFILES/sys.sh
fi

# Git tab completion and prompt.
source $DOTFILES/git/git-completion.bash
source $DOTFILES/git/bash-git-prompt/prompt-colors.sh
GIT_PROMPT_FETCH_REMOTE_STATUS=0
source $DOTFILES/git/bash-git-prompt/gitprompt.sh

source $DOTFILES/aliases.sh
