# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Aliases
alias ls="ls --color"
alias ll="ls -l"
alias la="ls -A"
alias cls="clear"
alias pytest='py.test-2.7'
alias pytest3='py.test-3.3'
alias grep="grep --color -n --mmap"
alias screen="screen -s bash" # Make sure bashrc gets executed in cygwin.

export VISUAL=vim

# Add home/bin to our path.
PATH=$HOME/bin:$PATH

# Add pear to our path
PATH=$HOME/pear:$PATH

DOTFILES=$HOME/.files

# Git tab completion and prompt.
source $DOTFILES/git/git-completion.bash
source $DOTFILES/git/git-colors.sh
source $DOTFILES/git/git-prompt.sh
#GIT_PS1_SHOWSTASHSTATE=1
#GIT_PS1_SHOWDIRTYSTATE=1

# Pip settings
PIP_VIRTUALENV_BASE=$WORKON_HOME
PIP_RESPECT_VIRTUALENV=true

# Default virtualenvwrapper settings
VIRTUALENVWRAPPER_PYTHON=python
VIRTUALENVWRAPPER_SH=virtualenvwrapper.sh
WORKON_HOME=$HOME/.envs

# System specific settings
if [ -f $DOTFILES/sys.sh ]; then
    source $DOTFILES/sys.sh
fi

# Virtualenvwrapper
if [ "$VIRTUALENVWRAPPER_SH" ]; then
    source $VIRTUALENVWRAPPER_SH
fi

if [ "$VIRTUAL_ENV" ]; then 
    source $VIRTUAL_ENV/bin/activate; 
fi 
