# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Aliases
alias mv="mv -i"
alias rm="rm -i"
alias cp="cp -i"
alias ls="ls --color"
alias ll="ls -l"
alias la="ls -A"
alias cls="clear"
alias tree="tree -C"
alias free="free -th"
alias grep="grep --color -n"
alias screen="screen -s bash" # Make sure bashrc gets executed in cygwin.

export VISUAL=vim

# Add home/bin to our path.
PATH=$HOME/bin:$PATH

# Add pear to our path
PATH=$HOME/pear:$PATH

DOTFILES=$HOME/.files

# Git tab completion and prompt.
source $DOTFILES/git/git-completion.bash
source $DOTFILES/git/bash-git-prompt/prompt-colors.sh
GIT_PROMPT_FETCH_REMOTE_STATUS=0
source $DOTFILES/git/bash-git-prompt/gitprompt.sh

# Default virtualenvwrapper settings
VIRTUALENVWRAPPER_SH=virtualenvwrapper.sh
WORKON_HOME=$HOME/.envs

# Pip settings
PIP_VIRTUALENV_BASE=$WORKON_HOME
PIP_RESPECT_VIRTUALENV=true

# System specific settings
if [ -f $DOTFILES/sys.sh ]; then
    source $DOTFILES/sys.sh
fi

# Virtualenvwrapper
if [ "$VIRTUALENVWRAPPER_SH" ]; then
    source $VIRTUALENVWRAPPER_SH
fi

# If we open a shell within a virtual env, make sure it's activated.
if [ "$VIRTUAL_ENV" ]; then 
    source $VIRTUAL_ENV/bin/activate; 
fi 

# Switch iTerm2 profile
it2prof() {
    echo -e "\033]50;SetProfile=$1\a"
}

light(){
    export THEME=light
    it2prof Light
}

dark(){
    export THEME=dark
    it2prof Default
}

# Default to dark theme
if [ "$THEME" = "light" ]
then
    light
else
    dark
fi
