
" General Settings "

set mouse=a
set bs=2
let mapleader = ","

" Use four spaces for indentation in general
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab

" Searching
set hlsearch
set ignorecase
set smartcase

" Backups and persistent undo
set undodir=~/.vim/tmp/undo//
set undofile
set undolevels=1000
set undoreload=10000
set backupdir=~/.vim/tmp/backup//
set backup

" Disable swap files.
set noswapfile

" Clipboard
set pastetoggle=<F2>
set clipboard=unnamed


" Custom Key Bindings "

" Quicksave with <Ctrl>-Z
noremap <C-Z> :update<CR>
vnoremap <C-Z> <C-C>:update<CR>
inoremap <C-Z> <C-O>:update<CR>

" Quick exit 
noremap <Leader>e :quit<CR>  " Quit current window
noremap <Leader>E :qa!<CR>   " Quit all windows

" Select all
map <Leader>a ggVG

" Easier tab switching
map <Leader>n <esc>:tabprevious<CR>
map <Leader>m <esc>:tabnext<CR>

" Sorting (very useful for alphabetizing python imports)
vnoremap <Leader>s :sort<CR>

" Disable arrow keys for navigation
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Move the cursor in insert mode by holding CTRL
imap <C-h> <C-o>h
imap <C-j> <C-o>j
imap <C-k> <C-o>k
imap <C-l> <C-o>l

" Indent and dedent with tab and shift-tab (very useful in visual block mode)
vnoremap < <gv
vnoremap > >gv
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
inoremap <S-Tab> <C-D>
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv


" Language Specific Settings "

" Force .md files to be read as markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" Use two spaces for indentation in ada
autocmd FileType ada setlocal shiftwidth=2 tabstop=2

" Smarty syntax highlighting
au BufRead,BufNewFile *.tpl set filetype=smarty


" Third Party Addons "

" Invoke pathogen to automagically load plugins, themes, etc.
call pathogen#infect()

" Theme / Appearance
set t_Co=256
color wombat

" Show whitespace
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red

" Line numbers, document width, and wrapping
set number  " show line numbers
set tw=79   " width of document (used by gd)
set nowrap  " don't automatically wrap on load
set fo-=t   " don't automatically wrap text when typing


" Plugin Settings "

" ctrlp
let g:ctrlp_max_height = 30
set wildignore+=*.pyc
set wildignore+=*build/*
set wildignore+=*dist/*
set wildignore+=*/coverage/*
set wildignore+=.tox*
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
set wildignore+=*node_modules*

" NerdTree 
nmap <silent> <C-D> :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.py[co]$', '__pycache__$']

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Snippets (UltiSnip + vim-snippets)
let g:UltiSnipsExpandTrigger="<NUL>"
let g:UltiSnipsListSnippets="<NUL><ENTER>"
