
DOTFILES=$HOME/.files
export PATH=$DOTFILES/bin:$PATH

# Virtualenvwrapper
WORKON_HOME=$HOME/.envs

# Pip 
PIP_VIRTUALENV_BASE=$WORKON_HOME
PIP_RESPECT_VIRTUALENV=true

# System specific settings
if [ -f $DOTFILES/sys.sh ]; then
    source $DOTFILES/sys.sh
fi

# If we open a shell within a virtual env, make sure it's activated.
if [ "$VIRTUAL_ENV" ]; then 
    source $VIRTUAL_ENV/bin/activate; 
fi 

# oh-my-zsh
export ZSH="$HOME/.files/oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(
    git
    docker
    iterm2
    virtualenvwrapper
    vscode
    kubectl
)
source $ZSH/oh-my-zsh.sh

source $DOTFILES/aliases.sh
