
zmodload zsh/zprof

export DOTFILES=$HOME/.files
export PATH=$DOTFILES/bin:$PATH

# Shared settings for bash & zsh
source $DOTFILES/prompt/common.sh

# Python (virtualenvwrapper, pip, etc.)
WORKON_HOME=$HOME/.envs
PIP_VIRTUALENV_BASE=$WORKON_HOME
PIP_RESPECT_VIRTUALENV=true
if [ "$VIRTUAL_ENV" ]; then 
    source $VIRTUAL_ENV/bin/activate; 
elif [ "virtualenvwrapper.sh" ]; then 
    source virtualenvwrapper_lazy.sh
fi

# macOS terminal themes
function light {
    iterm2_profile Light
    export USER_THEME="light"
}

function dark {
    iterm2_profile Default
    export USER_THEME="dark"
}


# oh-my-zsh
export ZSH="$HOME/.files/prompt/oh-my-zsh"
# ZSH_THEME="robbyrussell"
# ZSH_THEME="clean"
ZSH_THEME="daveverwer"
plugins=(
    # gitfast
    # docker
    # iterm2
    # python
    # tmux
    # kubectl
)
source $ZSH/oh-my-zsh.sh

# Shared aliases, etc.
source $DOTFILES/prompt/aliases.sh
