
- create:
    ~/.ssh:
      mode: 0700

- crossplatform-shell:
      - command: bw get notes ssh-key-private > ~/.ssh/id_ed25519
        platform: "!win32"
        description: Download ssh private key
      - command: bw get notes ssh-key-public > ~/.ssh/id_ed25519.pub
        platform: "!win32"
        description: Download ssh public key
      - command: bw get notes ssh-config > ~/.ssh/config
        platform: "!win32"
        description: Download ssh config 
      - command: bw get notes gitconfig > ~/.gitconfig
        description: Download git config 
