
- create:
    ~/.ssh:
      mode: 0700

- crossplatform-shell:
      - command: bws secret get 5c952460-3044-4264-910d-b22a011a132c | jq -r .value > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        platform: "!win32"
        description: Download ssh private key
        quiet: true
      - command: bws secret get 7f6b8fb6-8494-43d4-be62-b22a011f5f98 | jq -r .value > ~/.ssh/id_ed25519.pub && chmod 644 ~/.ssh/id_ed25519.pub
        platform: "!win32"
        quiet: true
        description: Download ssh public key
      - command: bws secret get d5d012b9-2ee2-46d0-811a-b22a011f717b | jq -r .value > ~/.ssh/config && chmod 600 ~/.ssh/config
        platform: "!win32"
        description: Download ssh config 
        quiet: true
      - command: bws secret get 8049a071-d630-4335-962a-b22a011f8559 | jq -r .value > ~/.gitconfig
        description: Download git config 
        quiet: true
