# TODO: mac settings eg: defaults write .GlobalPreferences com.apple.mouse.scaling -1

- defaults:
      link:
          relink: true
          create: true
      crossplatform-link:
          relink: true
          create: true
          force: true
          fallback_to_copy: true

- omnipkg:
    - install: [
        # Linux uses rust/cargo below
        {mac: mise},
        {mac: starship},

        fzf,
        git,
        git-lfs,
        neovim,
        [python3, python],
        {else: the_silver_searcher, apt: silversearcher-ag},
        tmux,
        zsh,
        rustup,
        jq,

        # Mac specific
        {mac: cormacrelf/tap/dark-notify},
        {mac: dark-mode},
        {mac: font-fira-code-nerd-font},
        {mac: karabiner-elements},
        {mac: keepingyouawake},
        {mac: nikitabobko/tap/aerospace},
        {mac: wezterm},
    ]

- clean: ["~"]

- crossplatform-shell:
      - command: rustup default stable
        platform: linux
        description: Use rustup to install stable toolchain
      - command: cargo install cargo-binstall
        platform: linux
        description: Install rust dependencies
      - command: cargo binstall mise starship bws
        platform: linux
        description: Install rust dependencies
      - command: mkdir ..\\AppData\\Local\\nvim
        platform: win32
        description: Ensure nvim directory exists on windows

- crossplatform-link:
      - ~/.wezterm.lua:
            path: config/wezterm.lua
            platform: "win32"
            force: true
            fallback_to_copy: true
      # This doesn't seem to work rn
      # - ~/Documents/Powershell/Microsoft.PowerShell_profile.ps1:
      #       path: misc/Powershell.ps1
      #       platform: "win32"
      #       force: true
      #       fallback_to_copy: true
      - ~/.config/starship.toml:
            path: config/starship.toml
      - ~/AppData/Local/nvim/init.lua:
            path: config/nvim.lua
            platform: "win32"
            force: true
            fallback_to_copy: true
            create: true

      - ~/.bashrc:
            path: config/bashrc
            platform: "!win32"
      - ~/.config/nvim/init.lua:
            path: config/nvim.lua
            platform: "!win32"
      - ~/.config/tmux/tmux.conf:
            path: config/tmux.conf
            platform: "!win32"
      - ~/.config/tmux/plugins/tpm:
            path: tpm
            platform: "!win32"
      - ~/.config/wezterm/wezterm.lua:
            path: config/wezterm.lua
            platform: "!win32"
      - ~/.config/mise/config.toml:
            path: config/mise.toml
            platform: "!win32"
      - ~/.vimrc:
            path: config/vimrc
            platform: "!win32"
      - ~/.zshrc:
            path: config/zshrc
            platform: "!win32"

      - ~/.config/karabiner/karabiner.json:
            path: config/karabiner.json
            platform: darwin
      - ~/.aerospace.toml:
            path: config/aerospace.toml
            platform: darwin

- crossplatform-shell:
      - command: defaults write com.apple.dock expose-group-apps -bool true && killall Dock
        platform: darwin
        quiet: true
        description: Adjust expose to work with aerospace
      - command: defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer
        platform: darwin
        quiet: true
        description: Adjust spaces spans-displays to work with aerospace

- shell:
      # Disabled mason update for now since it's not working on WSL
      - [nvim --headless "+Lazy! sync" +TSUpdate +qa, Installing neovim plugins]
      - [
            ~/.config/tmux/plugins/tpm/bin/install_plugins || true,
            Installing tmux plugins,
        ]
      # - [pipx install pdm, Installing pdm]
      - [mise install]
      - [pdm plugin add pdm-django, Installing django plugin for pdm]
