[tools]
bitwarden = "latest"
bitwarden-secrets-manager = "latest"
fzf = "latest"
neovim = "0.10"
node = "20.18.3"
pdm = "latest"
python = "3.13.2"
ripgrep = "latest"
starship = "latest"
uv = "latest"
watchexec = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[settings.python]
compile = false
