[tools]
bitwarden = "latest"
bitwarden-secrets-manager = "latest"
bun = "latest"
fzf = "latest"
neovim = "0.10"
node = "20.18.3"
pdm = "latest"
pipx = "latest"
python = "3.13.2"
starship = "latest"
uv = "latest"
